#ifndef VER_COMPANYNAME_STR
#define VER_COMPANYNAME_STR         "github/3F"
#endif
#ifndef VER_FILEDESCRIPTION_STR
#define VER_FILEDESCRIPTION_STR     "3F's IL assembler on coreclr"
#endif
#ifndef VER_INTERNALNAME_STR
#define VER_INTERNALNAME_STR        VER_FILEDESCRIPTION_STR
#endif
#ifndef VER_ORIGINALFILENAME_STR
#define VER_ORIGINALFILENAME_STR    VER_FILEDESCRIPTION_STR
#endif
#ifndef VER_PRODUCTNAME_STR
#define VER_PRODUCTNAME_STR         ".NET"
#endif
#undef VER_PRODUCTVERSION
#define VER_PRODUCTVERSION          00,00,00,00000
#undef VER_PRODUCTVERSION_STR
#define VER_PRODUCTVERSION_STR      VER_3FMOD_PRODUCT_STR
#undef VER_FILEVERSION
#define VER_FILEVERSION             00,00,00,00000
#undef VER_FILEVERSION_STR
#define VER_FILEVERSION_STR         "00.00.00.00000"
#ifndef VER_LEGALCOPYRIGHT_STR
#define VER_LEGALCOPYRIGHT_STR      "github/3F/coreclr"
#endif
#ifndef VER_DEBUG
#define VER_DEBUG                   VS_FF_DEBUG
#endif
#define VER_3FMOD_BSHA1_STR         ""
#define VER_3FMOD_BNAME_STR         ""
#define VER_3FMOD_BREV              0
#define VER_3FMOD_PRODUCT_STR       ""
